### PR TITLE
Set Form Entry before Options and Default Options

### PR DESCRIPTION
**Pull request by bloveless**
Setting the form entry before the setting the form options and default form options allows us to use the entry data in the form options. I.E. using the entry name (if it exists) in the form title.

### CODE REVIEW

**Comment by RyanThompson** [comment]
I can dig this - but, let's set it as soon as possible. Go!

**Comment by bloveless** [comment]
Alright so the order that made sense to me was SetFormModel -> SetFormStream -> Set Repository -> SetFormEntry -> then the rest

**Comment by bloveless** [comment]
@RyanThompson What do you think about this?

**Comment by RyanThompson** [comment]
Perfect! And if you need it earlier then you need to set it yourself ^_^

**Pull request merged**
