### PR TITLE
Hold shift to select checkmarks between clicks for selecting rows

### PR DESCRIPTION
**Pull request by Piterden**
When there are no one or only one selected, it toggles selection or select another element.
When there are multiple items selected it toggles only one leaving to other its state.

### CODE REVIEW

**Comment by Piterden** [comment]
Check the JS. There is no one DOM modification.

**Comment by Piterden** [comment]
@RyanThompson could you show what behavior you don't like?

**Comment by RyanThompson** [comment]
Meh

**Comment by Piterden** [comment]
What `meh` means?

**Comment by Piterden** [comment]
Hm. What's again?

**Pull request closed without merging**
