### PR TITLE
Allow the use of old in twig.

### PR DESCRIPTION
**Pull request by bloveless**

### CODE REVIEW

**Comment by RyanThompson** [comment]
`{{ request_old(key, default) }}` should work

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/blob/master/src/StreamsPlugin.php#L287

**Comment by bloveless** [comment]
Whoooooops! That worked :) Thanks!

**Comment by RyanThompson** [comment]
^_^

**Pull request closed without merging**
