### PR TITLE
Form "ctrl+s" and "ctrl+shift+s" handling

### PR DESCRIPTION
**Pull request by Piterden**
"ctrl+s" - fire first action
"ctrl+shift+s" - fire second action

### CODE REVIEW

**Comment by RyanThompson** [comment]
Woo hoo! Ill check it out thanks!

**Comment by Piterden** [comment]
It shouldn't works with `caps-lock` pressed for now.

I'll try to fix it later.

**Comment by RyanThompson** [comment]
I think this should go into the theme.. So while I will use this code and have it bookmarked I am going to close this for now - thank you!

**Comment by RyanThompson** [comment]
I changed my mind.. in core it goes! But will alter slightly from this - thank you!

**Comment by RyanThompson** [comment]
This has been added and will be included in the v3.2 release!

**Comment by Piterden** [comment]
Got you!

**Pull request closed without merging**
