### PR TITLE
|| and && should always placed at the end of the line

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Says who?

**Comment by Piterden** [comment]
Linter sad.
```php
if (
    myCondition1 &&
    myCondition2 ||
    myCondition3
)
```
But
```php
return myCondition
    ? exp1
    : exp2
```

**Comment by RyanThompson** [comment]
Which one?

**Comment by RyanThompson** [comment]
Hmm.. it's tough: https://stackoverflow.com/questions/23758916/psr-2-standard-for-long-if-conditions

**Comment by Piterden** [comment]
It would be better if we would have maximum similarity between JS and PHP code styles

**Comment by RyanThompson** [comment]
Expanded the line anyways - used to be longer

**Pull request closed without merging**
