### PR TITLE
Websemantics patch 1

### PR DESCRIPTION
**Pull request by websemantics**
This would allow to override the default module slug as namespace.

### CODE REVIEW

**Comment by RyanThompson** [comment]
I think what you are after is already accommodated here. 

The order of precedence is:

1.) The field namespace key
2.) The migration $namespace property
3.) The addon slug

**Comment by websemantics** [comment]
True, .. but when I set the $namespace property in migration file, i.e. `protected $namespace = 'core';` it gets overridden by the addon slug!

**Comment by RyanThompson** [comment]
I see - and this commit successfully allows both (the parenthesis make sense now.. Seems like Ive run into that before).

**Comment by RyanThompson** [comment]
can you look through those migrate / roll back commands and see if there is any more instances of this logic that needs to be replaced?

**Comment by websemantics** [comment]
For sure, .. I'm doing that right now ..

**Comment by RyanThompson** [comment]
You da man

**Comment by websemantics** [comment]
When uninstall a module, RollbackFieldsHandler leaves fields translation behind (should be deleted)

**Comment by RyanThompson** [comment]
That should be triggered? https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Model/Listener/DeleteTranslations.php

**Comment by RyanThompson** [comment]
If you can't push a fix open a new issue mkay? ^_^

**Pull request merged**
