### PR TITLE
Added .eslintrc.yml config

### PR DESCRIPTION
**Pull request by Piterden**
If you allow)

### CODE REVIEW

**Comment by RyanThompson** [comment]
What is this for? And I think we should ALWAYS indent with 4 spaces.

**Comment by Piterden** [comment]
.eslintrc is for configure linter.
JS is really more convenient with 2, but if you don't want, this is your right.

**Comment by RyanThompson** [comment]
I feel like this might be too personalized to be included.. thoughts?

**Comment by RyanThompson** [comment]
I have to close this one I do believe. IMO this reflects a _personal_ project file. I personally use my IDE to lint. Perhaps later on we'll rely on an auto CS service like Laravel does.

**Pull request closed without merging**
