### PR TITLE
remove unnecessary jquery.min.js

### PR DESCRIPTION
**Pull request by lnlion**
jquery has already loaded in theme.js

### CODE REVIEW

**Review by Piterden — COMMENTED** [review]
Haha, and how would the sortable plugin work without jQuery? Or it had been imported in some other place? Cause if so, i suppose fokken assetic would exclude repeats, lefting only code you need. But I am not fully sure, of course...

Why did you comment it? I would remove it fully on your place...

**Comment by lnlion** [comment]
see this https://github.com/anomalylabs/streams-platform/commit/3488a5564a4dcc98659b92e623a6ab049a4852bd

**Comment by lnlion** [comment]
and in accelerant-theme; you've already loaded jquery.min.js

**Comment by RyanThompson** [comment]
I removed this a bit ago and it's doing fine (forgot all about it). Thanks!

**Pull request closed without merging**
