### PR TITLE
Fixed findTrashed function

### PR DESCRIPTION
**Pull request by Piterden**
Without this fix force deleting and restoring entries wasn't succeed.

### CODE REVIEW

**Comment by Piterden** [comment]
#332 about this too

**Comment by RyanThompson** [comment]
`\Illuminate\Database\Eloquent\SoftDeletes` uses `trashed` where are you getting `withTrashed`?

**Comment by Piterden** [comment]
In several places:
```conf
Searching 12951 files for "withTrashed"

/home/den/projects/apex/core/anomaly/files-module/src/Folder/FolderRepository.php:
   41      {
   42          return $this->model
   43:             ->withTrashed()
   44              ->where('slug', $slug)
   45              ->first();

/home/den/projects/apex/vendor/anomaly/streams-platform/src/Model/EloquentRepository.php:
   64      {
   65          return $this->model
   66:             ->withTrashed()
   67              ->orderBy('id', 'ASC')
   68              ->where('id', $id)

/home/den/projects/apex/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphTo.php:
  268  
  269          // If we tried to call a method that does not exist on the parent Builder instance,
  270:         // we'll assume that we want to call a query macro (e.g. withTrashed) that only
  271          // exists on related models. We will just store the call and replay it later.
  272          catch (BadMethodCallException $e) {

/home/den/projects/apex/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletingScope.php:
   10       * @var array
   11       */
   12:     protected $extensions = ['ForceDelete', 'Restore', 'WithTrashed', 'WithoutTrashed', 'OnlyTrashed'];
   13  
   14      /**
   ..
   82      {
   83          $builder->macro('restore', function (Builder $builder) {
   84:             $builder->withTrashed();
   85  
   86              return $builder->update([$builder->getModel()->getDeletedAtColumn() => null]);
   ..
   94       * @return void
   95       */
   96:     protected function addWithTrashed(Builder $builder)
   97      {
   98:         $builder->macro('withTrashed', function (Builder $builder) {
   99              return $builder->withoutGlobalScope($this);
  100          });

7 matches across 4 files
```
Method `trashed()` returns boolean and can`t be used by query chain.
Please, correct me if I wrong.
```
Searching 12951 files for "trashed()" (case sensitive)

/home/den/projects/apex/core/anomaly/files-module/src/File/FileSynchronizer.php:
   70          } else {
   71  
   72:             if ($file->trashed()) {
   73                  $this->files->restore($file);
   74              }

/home/den/projects/apex/vendor/anomaly/streams-platform/src/Entry/Contract/EntryInterface.php:
  322       * @return bool
  323       */
  324:     public function trashed();
  325  
  326      /**

/home/den/projects/apex/vendor/anomaly/streams-platform/src/Model/EloquentModel.php:
  735       * @return bool
  736       */
  737:     public function trashed()
  738      {
  739:         return parent::trashed();
  740      }
  741  

/home/den/projects/apex/vendor/anomaly/streams-platform/src/Ui/Table/Component/Action/Handler/ForceDelete.php:
   31          foreach ($selected as $id) {
   32              if ($entry = $repository->findTrashed($id)) {
   33:                 if ($entry->trashed() && $repository->forceDelete($entry)) {
   34                      $builder->fire('row_deleted', compact('builder', 'model', 'entry'));
   35  

/home/den/projects/apex/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletes.php:
   99       * @return bool
  100       */
  101:     public function trashed()
  102      {
  103          return ! is_null($this->{$this->getDeletedAtColumn()});

6 matches across 5 files
```

**Comment by Piterden** [comment]
Here in docs:

https://laravel.com/docs/5.3/eloquent#querying-soft-deleted-models

**Comment by Piterden** [comment]
I've made `composer update` and after that I can't make force deleting of entry with `Call to a member function orderBy() on boolean` error!

```
Whoops, looks like something went wrong.

1/1
FatalThrowableError in EloquentRepository.php line 67:
Call to a member function orderBy() on boolean
in EloquentRepository.php line 67
at EloquentRepository->findTrashed('2') in ForceDelete.php line 32
at ForceDelete->handle(object(ReviewTableBuilder), object(EloquentRepository), array('2'))
at call_user_func_array(array(object(ForceDelete), 'handle'), array(object(ReviewTableBuilder), object(EloquentRepository), array('2'))) in Container.php line 508
at Container->call(array(object(ForceDelete), 'handle'), array('builder' => object(ReviewTableBuilder), 'selected' => array('2'))) in Container.php line 603
at Container->callClass('Anomaly\Streams\Platform\Ui\Table\Component\Action\Handler\ForceDelete@handle', array('builder' => object(ReviewTableBuilder), 'selected' => array('2')), null) in Container.php line 503
at Container->call('Anomaly\Streams\Platform\Ui\Table\Component\Action\Handler\ForceDelete@handle', array('builder' => object(ReviewTableBuilder), 'selected' => array('2'))) in ActionExecutor.php line 120
at ActionExecutor->execute(object(ReviewTableBuilder), object(Action)) in ExecuteAction.php line 41
at ExecuteAction->handle(object(ActionExecutor))
at call_user_func_array(array(object(ExecuteAction), 'handle'), array(object(ActionExecutor))) in Container.php line 508
at Container->call(array(object(ExecuteAction), 'handle')) in Dispatcher.php line 94
at Dispatcher->Illuminate\Bus\{closure}(object(ExecuteAction)) in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(ExecuteAction)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Dispatcher.php line 98
at Dispatcher->dispatchNow(object(ExecuteAction)) in Dispatcher.php line 75
at Dispatcher->dispatch(object(ExecuteAction)) in DispatchesJobs.php line 17
at PostTable->dispatch(object(ExecuteAction)) in PostTable.php line 51
at PostTable->handle(object(Request), object(ResponseFactory))
at call_user_func_array(array(object(PostTable), 'handle'), array(object(Request), object(ResponseFactory))) in Container.php line 508
at Container->call(array(object(PostTable), 'handle')) in Dispatcher.php line 94
at Dispatcher->Illuminate\Bus\{closure}(object(PostTable)) in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(PostTable)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Dispatcher.php line 98
at Dispatcher->dispatchNow(object(PostTable)) in Dispatcher.php line 75
at Dispatcher->dispatch(object(PostTable)) in DispatchesJobs.php line 17
at TableBuilder->dispatch(object(PostTable)) in TableBuilder.php line 178
at TableBuilder->post() in TableBuilder.php line 149
at TableBuilder->make() in TableBuilder.php line 191
at TableBuilder->render() in ReviewsController.php line 18
at ReviewsController->index(object(ReviewTableBuilder))
at call_user_func_array(array(object(ReviewsController), 'index'), array(object(ReviewTableBuilder))) in Controller.php line 55
at Controller->callAction('index', array(object(ReviewTableBuilder))) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(ReviewsController), 'index') in Route.php line 189
at Route->runController() in Route.php line 144
at Route->run(object(Request)) in Router.php line 653
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ApplicationReady.php line 49
at ApplicationReady->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SetLocale.php line 88
at SetLocale->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in PoweredBy.php line 38
at PoweredBy->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AuthorizeRoutePermission.php line 106
at AuthorizeRoutePermission->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AuthorizeControlPanel.php line 51
at AuthorizeControlPanel->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AuthorizeModuleAccess.php line 63
at AuthorizeModuleAccess->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AuthorizeRouteRoles.php line 98
at AuthorizeRouteRoles->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckSecurity.php line 86
at CheckSecurity->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Router.php line 655
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 629
at Router->dispatchToRoute(object(Request)) in Router.php line 607
at Router->dispatch(object(Request)) in Kernel.php line 268
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 150
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
at Kernel->handle(object(Request)) in index.php line 53
```
That because we have this code in `EloquentRepository.php` file:
```php
<?php
    /**
     * Find a trashed record by it's ID.
     *
     * @param $id
     * @return null|EloquentModel
     */
    public function findTrashed($id)
    {
        return $this->model
            ->trashed() // {Boolean} 
            ->orderBy('id', 'ASC')
            ->where('id', $id)
            ->first();
    }
```
Really - we have `boolean` there! We need to use `withTrashed()` or `onlyTrashed()` methods to receive `QueryBuilder` in that place.
If you prefer `onlyTrashed()`, I could make corrects in this PR. 
I'd appreciate, if you could merge it bit quicker, because I have more then one Pyro sites.

**Comment by Piterden** [comment]
Another one same issue
screencapture-apex-web812-pro-admin-files-1482712040615

**Comment by Piterden** [comment]
selection_137

And everything is successful with fix from this PR)

**Pull request merged**
