### PR TITLE
Cannot use getimagesize on images from files module since php doesn\'…

### PR DESCRIPTION
**Pull request by bloveless**
…t know where those files are

### CODE REVIEW

**Comment by RyanThompson** [comment]
This isn't really a fix we need height / width

**Comment by bloveless** [comment]
There needs to be something similar to $image = $this->paths->realPath($image); from the block above it, but I'm not sure what it should be. I did try the realPath function there, but it only works if the string has a '::' in it.

**Comment by RyanThompson** [comment]
I'll check on a puter - if it's just that string identifier maybe this is ok.. Or we can load the resource or something

**Comment by bloveless** [comment]
That particular section seems to only deal with string identifiers that don't start with http or https. I.E. local:// and it barfs when it gets one of those. I suppose it only throws a warning, but warnings = errors

**Comment by RyanThompson** [comment]
Try loading it with the mount manager / it's done elsewhere in that very same class

**Comment by bloveless** [comment]
I can't imagine that this is what you are looking for, but hey... it's really late, and I made the bastard work.

**Comment by RyanThompson** [comment]
Just ended up taking that out - not supported there

**Pull request closed without merging**
