### PR TITLE
Removed nobr tags

### PR DESCRIPTION
**Pull request by Piterden**
I was had to remove it cause of a mobile issue with buttons. It's better to use CSS for that behavior.

### CODE REVIEW

**Comment by dwainscheeren** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr

**Comment by Piterden** [comment]
What you wanted to say?

**Comment by dwainscheeren** [comment]
It needs to be removed indeed because it's not supported

**Comment by RyanThompson** [comment]
Thanks @Piterden !

**Pull request merged**
