### PR TITLE
Fixed unnecessary calling of the email value

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by Piterden** [comment]
Ya I understand about excess checking

**Comment by RyanThompson** [comment]
Not the responsibility of this class!

**Comment by Piterden** [comment]
Maybe you could explain a little bit more detailed?

**Comment by RyanThompson** [comment]
SRP - By the time the target gets here we should know it’s resolvable. 

I think the fix should go in settings / preferences.

**Pull request closed without merging**
