### PR TITLE
1.2

### PR DESCRIPTION
**Pull request by mattcdavis1**
This update allows for conditional twig caching.  This is useful for dev environment when you typically don't want to cache content - even if it is in cache tags.

### CODE REVIEW

**Comment by RyanThompson** [comment]
Going to change this to TWIG_CACHE and default to true

**Comment by mattcdavis1** [comment]
great - thanks!

**Comment by mattcdavis1** [comment]
@RyanThompson - just pulled in this update.  Looks like you missed a find / replace [here](https://github.com/datacodesolutions/streams-platform/blob/83e066ce0e2adb521dbc83670a4fbf3447f414ac/src/View/Cache/CacheAdapter.php#L54)

**Comment by RyanThompson** [comment]
Thanks Matt - got it!

**Comment by mattcdavis1** [comment]
one last thing - looks like on that second twig cache it's not defaulting to true (line 55)

**Pull request merged**
