### PR TITLE
Update to Twig 2.x

### PR DESCRIPTION
**Pull request by schmidex**
I didn't find any problems with this...

### CODE REVIEW

**Comment by Piterden** [comment]
Me too

**Comment by RyanThompson** [comment]
You guys have thoroughly tested this out? Have you tested any PRO addons by chance? Where are the breaking changes documented? If any

**Comment by schmidex** [comment]
Actually this fixes some deprecation warnings with the current twig version.
I'm no PRO User... So this is untested.
You can read about the deprecations here: http://symfony.com/blog/twig-how-to-upgrade-to-2-0-deprecation-notices-to-the-rescue
Couldn't find anything about breaking changes.

**Comment by Piterden** [comment]
What changes in API?

**Comment by RyanThompson** [comment]
There is a dependency that's blocking this atm

**Comment by RyanThompson** [comment]
```
Ryans-MacBook-Pro:workbench.local ryanthompson$ composer why twig/twig
anomaly/streams-platform        v1.2.248  requires  twig/twig (~1.0)       
aptoma/twig-markdown            2.0.0     requires  twig/twig (~1.12)      
asm89/twig-cache-extension      1.3.2     requires  twig/twig (^1.0|^2.0)  
phive/twig-extensions-deferred  v0.3.0    requires  twig/twig (~1.18)      
rcrowe/twigbridge               v0.9.4    requires  twig/twig (~1.30)  
```

**Comment by RyanThompson** [comment]
Had to revert - but will give it another shot tomorrow

**Comment by Piterden** [comment]
Markdown https://packagist.org/packages/jralph/twig-markdown

**Comment by Piterden** [comment]
http://symfony.com/blog/twig-how-to-upgrade-to-2-0-deprecation-notices-to-the-rescue
Doesn't it should be something like ^ ?

**Comment by schmidex** [comment]
Seems like some librarys are not official supported to use twig 2.0.
Sorry this worked fine when requiring twig 2.3.0 as 1.33.
I will keep an eye on the missing dependencies (twig-markdown and twigbridge) and open a new pull request as soon as these are ready.

**Pull request merged**
