### PR TITLE
Copy field slug button

### PR DESCRIPTION
**Pull request by Piterden**
image

### CODE REVIEW

**Comment by Piterden** [comment]
We could copy something else with shift button pressed.

**Comment by Piterden** [comment]
Have bug with nested forms now

**Comment by RyanThompson** [comment]
I think this is best left out of the UI. There are the fields tables generally or assignments but.. idk I feel like while there is a need to know what's available - the people who need that should not be mucking up the UI for the end user. Docs generally have attributes. 

I'll have to think on a good way to expose this to the appropriate audience.

**Comment by Piterden** [comment]
It is awesome! )

**Pull request closed without merging**
