### PR TITLE
Forms should allow columns

### PR DESCRIPTION
**Pull request by bloveless**
Normalize sections array in fields. "grid_size" option for normalization.

### CODE REVIEW

**Comment by markbratanov** [comment]
YES. 

this was much needed. thank you a lot!

**Comment by bloveless** [comment]
No problem!

**Comment by bloveless** [comment]
Just for reference. I tested this on the pages form, the users form, a custom module form, and a custom front end form.

**Comment by markbratanov** [comment]
This makes my day!

**Pull request merged**
