### PR TITLE
Add tool-tip with field slug to the label of each field

### PR DESCRIPTION
**Pull request by Piterden**
Please, let's add it. It's half of line, but promised to be very useful.

### CODE REVIEW

**Comment by RyanThompson** [comment]
I'd prefer not - there is no reason the user would need to know this and the developer can very easily find it.

**Comment by Piterden** [comment]
Do you understand that it takes a time?

**Comment by RyanThompson** [comment]
Takes time to look up the slug or takes time to make this PR?

**Comment by Piterden** [comment]
Look at the slug in inspector or somewhere else takes much time in sum

**Comment by Piterden** [comment]
think disabled / enabled would do the trick )))

**Comment by RyanThompson** [comment]
There are much faster ways to do this. I usually have my DB open, there is always a slugs in the fields section of supported addons, and I usually guess based on the name. 

At this stage - I really want to avoid throwing a bunch of on/off options at the system. That can really get out of hand very quickly. Let me know what/how you're working on your application and I can help you find / determine slugs very quickly. But honestly this is the first I've heard of a suggestion like this too - I think that's a sign of it not being an urgent matter but maybe something in your workflow that might be improved.

**Comment by Piterden** [comment]
Ok, this is variables stream:
```json
[
	{
		"id" : 1,
		"sort_order" : 1,
		"created_at" : "2017-04-13 03:59:35",
		"created_by_id" : 1,
		"updated_at" : "2017-04-13 13:12:42",
		"updated_by_id" : 1,
		"sinij_tekst_sverhu" : "Когда риск обходится слишком дорого, приятно иметь дело с надёжными партнерами.  Нервный и кризисный 2016 год стал хорошим тестом на доверие: за год компания АПЕКС увеличила количество поставок вдвое. Сегодня с нами работают 200 розничных и оптовых компаний в 60 регионах России. Это выгодное сотрудничество, и вот почему.",
		"video" : null,
		"video_soderzhimoe" : "В компании из 70 человек 30 — технологи. Все тонкости объясняем на вашем родном языке и в вашем часовом поясе. Реагируем на запросы в течении одного рабочего дня, проводим все необходимые тесты.  Чтобы держать руку на пульсе, технологи каждый год повышают свою квалификацию на заводах производителей.",
		"video_zagolovok" : "Самая крупная техподдержка в стране",
		"obuchayushie_kursy" : "Современный учебный центр",
		"obuchayushie_kursy_soderzhimoe" : "Мы проводим обучающие курсы для специалистов вашей компании, а также ваших партнёров и клиентов. Умеем рассказывать о сложном так, чтобы было понятно каждому.",
		"reklamnaya_podderzhka_zagolovok" : "Максимальная рекламная поддержка",
		"reklamnaya_podderzhka_soderzhimoe" : "Доступна всем, кто начинает работать с нами. Компания АПЕКС ведёт крупнейшую по теме группу В Контакте и популярный канал на YouTube. Реклама — задача штатных сотрудников, потому что ни одно агентство не расскажет об адгезии на пластик так, как это делаем мы.  Мы пришлём все необходимые материалы для вашего сайта, буклеты и сувенирную продукцию.",
		"reklamnaya_podderzhka_tekst_snizu" : "Хотите сделать рекламную кампанию в вашем регионе? Поможем!",
		"pryamaya_svyaz_s_pokupatelyami_zagolovok" : "Прямая связь с покупателями",
		"pryamaya_svyaz_s_pokupatelyami_video" : null,
		"pryamaya_svyaz_s_pokupatelyami_soderzhimoe" : "Помогает вам продавать материалы подготовленным людям, которые уже знают их полезные свойства. Мы проводим мастер-классы, вебинары, баттлы с честным сравнением материалов и полезные тесты, до которых обычно ни у кого не доходят руки.  Отдельное направление нашей работы — рассказать и показать потребителям, что скупой платит дважды.",
		"pryamaya_svyaz_s_pokupatelyami_tekst_snizu" : "Отправьте запрос менеджеру, чтобы мы разработали для вас выгодные индивидуальные условия",
		"zagolovok_ryada_4" : "Мы помогаем работать быстрее, качественнее, и зарабатывать больше"
	}
]
```
You didn't see William's DB, yet. We could ask him if you want.

**Comment by Piterden** [comment]
Actually, coping to clipboard by label click should be perfect!

**Comment by RyanThompson** [comment]
That's not a bad idea

**Comment by Piterden** [comment]
Hope it means, I could try.

**Comment by RyanThompson** [comment]
Ya let’s get that in I think that’s a nice non-invasive approach. 

Maybe dev it like a plugin so it can be used elsewhere too.

**Comment by RyanThompson** [comment]
Use jquery btw - we want it like $(foo).clickCopy(options);

**Comment by Piterden** [comment]
Why do you think that it is $ does it?

I have in Pure: `posts.featured(3)`. Just like you have in PHP.

Then in template:
image

And this is an Array:
image

Of course not native - extending native Array is evil.
I could present to you that my collection, if you want...

PS Gotcha about $

**Pull request closed without merging**
