### PR TITLE
Added Hungarian language (hu)

### PR DESCRIPTION
**Pull request by kiger**

### CODE REVIEW

**Comment by RyanThompson** [comment]
This is awesome! But please resubmit to the develop branch of streams please. Per the contribution guidelines if there is a dev branch - submit to that. Only submit to the master if no dev branch exists ^_^

**Comment by RyanThompson** [comment]
Just a heads up - I pulled this in but submit to develop branch next time! Most the other repos have master branches, just so happens this one has a dev branch as well. 

Thanks!

**Comment by kiger** [comment]
Hello!
I'm trying to send PR to the other modules, but I've stucked, sor example the anomalylabs/addon-field_type I only see the master branch, if I choose the dev branch I get the "Choose different branches or forks above to discuss and review changes." and I cannot send the PR. I don't understand what went wrong.

**Comment by kiger** [comment]
OK, I've misunderstand that. I've sent the PR-s, can you check it?
Thanks.

**Comment by RyanThompson** [comment]
You're spot on! Many thanks for the translations.

**Pull request merged**
