### PR TITLE
Added clinging of `thead` to the top during scroll

### PR DESCRIPTION
**Pull request by Piterden**
cling

### CODE REVIEW

**Comment by designbywilliam** [comment]
Nice one @Piterden

**Comment by RyanThompson** [comment]
Look at you fancy pants!

**Comment by Piterden** [comment]
Maybe it need separate file?

**Comment by RyanThompson** [comment]
I think it's fine in this file - but it's pretty big compared to using jQuery. Nice and tight now!

**Comment by Piterden** [comment]
https://github.com/pyrocms/accelerant-theme/pull/18

**Pull request closed without merging**
