### PR TITLE
EloquentModel toArray return with relations

### PR DESCRIPTION
**Pull request by girvydas**
EloquentModel function toArray should return data with relations.
Parent (Illuminate\Database\Eloquent\Model) returns with relations so, this should too.

### CODE REVIEW

**Comment by schmidex** [comment]
I really would like to have this feature. Cause it allows to include releations when outputting json (for an api or similar use cases).
But this really seems to kill the whole application. 
Nginx returns "502 Bad Gateway". Apache "500 Internal Server Error"
Strange thing is, it worked for the first few hours (on nginx).
@RyanThompson any help on this? Or impossible?

**Comment by Piterden** [comment]
Show error output stack trace

**Comment by schmidex** [comment]
`nginx_error.log`:

```
2017/10/08 03:09:18 [error] 17320#5820: *6 WSARecv() failed (10054: FormatMessage() error:(15100)) while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9003", host: "jcw.test"
2017/10/08 03:09:18 [warn] 17320#5820: *6 upstream server temporarily disabled while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9003", host: "jcw.test"
2017/10/08 03:09:49 [error] 17320#5820: *6 WSARecv() failed (10054: FormatMessage() error:(15105)) while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "jcw.test"
2017/10/08 03:09:49 [warn] 17320#5820: *6 upstream server temporarily disabled while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "jcw.test"
2017/10/08 03:10:19 [error] 17320#5820: *6 WSARecv() failed (10054: FormatMessage() error:(15105)) while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "jcw.test"
2017/10/08 03:10:19 [warn] 17320#5820: *6 upstream server temporarily disabled while reading response header from upstream, client: 127.0.0.1, server: jcw.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "jcw.test"

```

**Comment by Piterden** [comment]
It is Nginx error log

**Comment by schmidex** [comment]
yeah. Cause nginx/php is "crashing".
Laravel logs don't show any errors.

**Comment by Piterden** [comment]
App debug enabled? Errors in PHP ini on?

**Comment by schmidex** [comment]
of course.
I tried 3 different enviroments (windows, osx, centOS) and two different webservers (nginx, apache).
this seems to take too much performance to get handled by the webserver

**Comment by Piterden** [comment]
Have you tried to use `parent::`?

**Comment by schmidex** [comment]
you mean like deleting the `toArray()` method from `EloquentModel` so that the original laravel method gets called?

This "works" but doesn't include the relations

**Comment by RyanThompson** [comment]
Where we at with this? This can actually be done already with formatters in the API module. My concern here is performance. Automatically including relations in toArray is very aggressive in my opinion.

**Comment by RyanThompson** [comment]
This tosses a 500 into things on my workbench installation. API has this handled with opt-in formatters. I think we'll leave this up to developers to add to their arrays as needed.

**Pull request closed without merging**
