### PR TITLE
localization: adding ar folder to Lang

### PR DESCRIPTION
**Pull request by aldf**

### CODE REVIEW

**Comment by aldf** [comment]
this necessary because otherwise when changing the language from Pyrocms Admin footer  it will display   only the translation and cache the old scss files that mean no changing to RTL or LTR

**Comment by RyanThompson** [comment]
Please undo the changes to the application so that this is ONLY a localization change. I have an easier method I will implement when I merge in the RTL change. No need to clear assets.

**Comment by aldf** [comment]
OK , done.

**Comment by RyanThompson** [comment]
Fantastic - thank you!

**Pull request merged**
