### PR TITLE
Added `make:seeder` artisan command

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Nicely done and thank you! Sorry it's taken so long for me to review - just getting into this stuff.

**Comment by Piterden** [comment]
Cool)
I thought it did something wrong with this seeder.

Instead of review you can just try it.

Thanks for updating Pyro in time...

**Comment by RyanThompson** [comment]
I am getting to and very much appreciate the composer updates too! I’ve been dreading them (all marked in my email) cause there are so many lmao.. but they are needed especially now with 1.1 vs 1.2 out.

Thanks again!

**Comment by Piterden** [comment]
I hope that marks makes you to think about right dependencies inside Pyro and Streams distributions. ))

If serious - I sorry about this too. I promise to try not to do same in the future.

**Comment by RyanThompson** [comment]
Oh no I very much appreciate it! I should have done it in the first place :-P

Totally my fault - thanks for your efforts!

**Comment by Piterden** [comment]
For this functionality was made an extension https://github.com/Piterden/seeder_make-extension

**Pull request closed without merging**
